[package]
name = "test_api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.2", features = ["json"] }
tokio = { version = "1.36.0", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_derive = "1.0.197"
dotenv = "0.15.0"
